language: python
python:
  - 2.7
addons:
  apt_packages:
    - pandoc
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r dev_requirements.txt
before_script:
  - mv mysite/mysite/settings/local_conf_example.py mysite/mysite/settings/local_conf.py
script:
  - python mysite/manage.py test
sudo: false
