language: python
python:
  - 2.7
  - 3.4
addons:
  apt_packages:
    - pandoc
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r dev_requirements.txt
script:
  - python mysite/manage.py test
sudo: false
